import './globals.css';

export function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
